{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "859e83dc",
   "metadata": {
    "_cell_guid": "757f7df2-4bb4-421d-ad25-86efd4d77918",
    "_uuid": "1a7c8e0a-f882-4307-bece-8c5a7f8e4607",
    "collapsed": false,
    "execution": {
     "iopub.execute_input": "2026-07-21T21:22:52.851793Z",
     "iopub.status.busy": "2026-07-21T21:22:52.851517Z",
     "iopub.status.idle": "2026-07-21T22:29:57.140187Z",
     "shell.execute_reply": "2026-07-21T22:29:57.139413Z"
    },
    "jupyter": {
     "outputs_hidden": false
    },
    "papermill": {
     "duration": 4024.294882,
     "end_time": "2026-07-21T22:29:57.142507+00:00",
     "exception": false,
     "start_time": "2026-07-21T21:22:52.847625+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO - Using device: cuda\n",
      "100%|██████████| 1.56G/1.56G [00:33<00:00, 47.1MB/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🚀 Using 2 GPUs for training!\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO - Network Architecture Initialized\n",
      "INFO - --> Starting from scratch (no previous models loaded).\n",
      "INFO - Epoch 1 | Train Loss: 1.9310 | Test Loss: 0.0274 | Test Acc: 41.48%\n",
      "INFO - Epoch 2 | Train Loss: 1.6561 | Test Loss: 0.0245 | Test Acc: 46.22%\n",
      "INFO - Epoch 3 | Train Loss: 1.4593 | Test Loss: 0.0286 | Test Acc: 47.01%\n",
      "INFO - Epoch 4 | Train Loss: 1.3196 | Test Loss: 0.0273 | Test Acc: 51.90%\n",
      "INFO - Epoch 5 | Train Loss: 1.2403 | Test Loss: 0.0176 | Test Acc: 64.99%\n",
      "INFO - Epoch 6 | Train Loss: 1.1528 | Test Loss: 0.0238 | Test Acc: 55.69%\n",
      "INFO - Epoch 7 | Train Loss: 1.0805 | Test Loss: 0.0187 | Test Acc: 61.78%\n",
      "INFO - Epoch 8 | Train Loss: 1.0293 | Test Loss: 0.0169 | Test Acc: 65.66%\n",
      "INFO - Epoch 9 | Train Loss: 0.9746 | Test Loss: 0.0198 | Test Acc: 61.27%\n",
      "INFO - Epoch 10 | Train Loss: 0.9188 | Test Loss: 0.0167 | Test Acc: 67.64%\n",
      "INFO - Epoch 11 | Train Loss: 0.8863 | Test Loss: 0.0154 | Test Acc: 69.45%\n",
      "INFO - Epoch 12 | Train Loss: 0.8578 | Test Loss: 0.0161 | Test Acc: 70.62%\n",
      "INFO - Epoch 13 | Train Loss: 0.8179 | Test Loss: 0.0154 | Test Acc: 70.52%\n",
      "INFO - Epoch 14 | Train Loss: 0.7807 | Test Loss: 0.0116 | Test Acc: 77.83%\n",
      "INFO - Epoch 15 | Train Loss: 0.7489 | Test Loss: 0.0129 | Test Acc: 76.08%\n",
      "INFO - Epoch 16 | Train Loss: 0.7354 | Test Loss: 0.0111 | Test Acc: 77.99%\n",
      "INFO - Epoch 17 | Train Loss: 0.7038 | Test Loss: 0.0125 | Test Acc: 75.29%\n",
      "INFO - Epoch 18 | Train Loss: 0.6752 | Test Loss: 0.0143 | Test Acc: 73.94%\n",
      "INFO - Epoch 19 | Train Loss: 0.6697 | Test Loss: 0.0116 | Test Acc: 77.32%\n",
      "INFO - Epoch 20 | Train Loss: 0.6371 | Test Loss: 0.0135 | Test Acc: 75.24%\n",
      "INFO - Epoch 21 | Train Loss: 0.6202 | Test Loss: 0.0124 | Test Acc: 76.43%\n",
      "INFO - Epoch 22 | Train Loss: 0.5978 | Test Loss: 0.0129 | Test Acc: 75.13%\n",
      "INFO - Epoch 23 | Train Loss: 0.5741 | Test Loss: 0.0099 | Test Acc: 81.02%\n",
      "INFO - Epoch 24 | Train Loss: 0.5863 | Test Loss: 0.0127 | Test Acc: 74.96%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 25 | Train Loss: 0.5535 | Test Loss: 0.0110 | Test Acc: 78.55%\n",
      "INFO - Epoch 26 | Train Loss: 0.5437 | Test Loss: 0.0157 | Test Acc: 72.31%\n",
      "INFO - Epoch 27 | Train Loss: 0.5153 | Test Loss: 0.0109 | Test Acc: 78.27%\n",
      "INFO - Epoch 28 | Train Loss: 0.5133 | Test Loss: 0.0135 | Test Acc: 73.55%\n",
      "INFO - Epoch 29 | Train Loss: 0.5083 | Test Loss: 0.0123 | Test Acc: 78.29%\n",
      "INFO - Epoch 30 | Train Loss: 0.4829 | Test Loss: 0.0120 | Test Acc: 77.96%\n",
      "INFO - Epoch 31 | Train Loss: 0.4974 | Test Loss: 0.0118 | Test Acc: 79.21%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 32 | Train Loss: 0.4564 | Test Loss: 0.0106 | Test Acc: 80.56%\n",
      "INFO - Epoch 33 | Train Loss: 0.4419 | Test Loss: 0.0129 | Test Acc: 75.75%\n",
      "INFO - Epoch 34 | Train Loss: 0.4354 | Test Loss: 0.0093 | Test Acc: 82.14%\n",
      "INFO - Epoch 35 | Train Loss: 0.4143 | Test Loss: 0.0097 | Test Acc: 82.90%\n",
      "INFO - Epoch 36 | Train Loss: 0.4260 | Test Loss: 0.0082 | Test Acc: 84.41%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 37 | Train Loss: 0.3952 | Test Loss: 0.0123 | Test Acc: 79.18%\n",
      "INFO - Epoch 38 | Train Loss: 0.4065 | Test Loss: 0.0087 | Test Acc: 83.13%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 39 | Train Loss: 0.3937 | Test Loss: 0.0108 | Test Acc: 80.08%\n",
      "INFO - Epoch 40 | Train Loss: 0.3807 | Test Loss: 0.0089 | Test Acc: 83.87%\n",
      "INFO - Epoch 41 | Train Loss: 0.3699 | Test Loss: 0.0096 | Test Acc: 82.75%\n",
      "INFO - Epoch 42 | Train Loss: 0.3693 | Test Loss: 0.0095 | Test Acc: 83.67%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 43 | Train Loss: 0.3400 | Test Loss: 0.0180 | Test Acc: 71.49%\n",
      "INFO - Epoch 44 | Train Loss: 0.3516 | Test Loss: 0.0111 | Test Acc: 80.36%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 45 | Train Loss: 0.3204 | Test Loss: 0.0100 | Test Acc: 82.78%\n",
      "INFO - Epoch 46 | Train Loss: 0.3492 | Test Loss: 0.0109 | Test Acc: 82.19%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 47 | Train Loss: 0.3128 | Test Loss: 0.0087 | Test Acc: 84.38%\n",
      "INFO - Epoch 48 | Train Loss: 0.3013 | Test Loss: 0.0091 | Test Acc: 85.10%\n",
      "INFO - Epoch 49 | Train Loss: 0.2989 | Test Loss: 0.0083 | Test Acc: 84.66%\n",
      "INFO - Epoch 50 | Train Loss: 0.3054 | Test Loss: 0.0120 | Test Acc: 81.48%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 51 | Train Loss: 0.2872 | Test Loss: 0.0088 | Test Acc: 84.69%\n",
      "INFO - Epoch 52 | Train Loss: 0.2894 | Test Loss: 0.0101 | Test Acc: 83.16%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 53 | Train Loss: 0.2900 | Test Loss: 0.0088 | Test Acc: 84.69%\n",
      "INFO - --> Loss plateaued. Patience: 2/3\n",
      "INFO - Epoch 54 | Train Loss: 0.2861 | Test Loss: 0.0086 | Test Acc: 85.12%\n",
      "INFO - Epoch 55 | Train Loss: 0.2931 | Test Loss: 0.0101 | Test Acc: 82.60%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 56 | Train Loss: 0.2584 | Test Loss: 0.0097 | Test Acc: 84.92%\n",
      "INFO - Epoch 57 | Train Loss: 0.2661 | Test Loss: 0.0082 | Test Acc: 85.02%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 58 | Train Loss: 0.2583 | Test Loss: 0.0165 | Test Acc: 76.64%\n",
      "INFO - --> Loss plateaued. Patience: 2/3\n",
      "INFO - Epoch 59 | Train Loss: 0.2580 | Test Loss: 0.0093 | Test Acc: 84.03%\n",
      "INFO - --> Loss plateaued. Patience: 3/3\n",
      "INFO - Stopping early at epoch 59! No improvement in 3 epochs.\n",
      "INFO - Saved new checkpoint: /kaggle/working/model_20260721_212408.pth\n",
      "INFO - Running final evaluation...\n",
      "INFO - Successfully appended execution results to /kaggle/working/results.csv\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import csv\n",
    "import glob\n",
    "import logging\n",
    "from datetime import datetime\n",
    "from dataclasses import dataclass\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "import torchvision\n",
    "import torchvision.transforms as transforms\n",
    "from torch.utils.data import DataLoader\n",
    "from torch.utils.tensorboard import SummaryWriter\n",
    "from torchvision.transforms import v2\n",
    "from torchvision.models.resnet import BasicBlock\n",
    "\n",
    "# =====================================================================\n",
    "# 1. CONFIGURATION (Notebook Friendly)\n",
    "# =====================================================================\n",
    "@dataclass\n",
    "class Config:\n",
    "    \"\"\"Replaces argparse for seamless Jupyter Notebook usage.\"\"\"\n",
    "    use_latest_model: bool = True\n",
    "    train_model: bool = True       # Set to False if you only want to evaluate\n",
    "    batch_size: int = 64 # let's try mini-batch SGD now. # increasing because GPU utilization is low.\n",
    "    learning_rate: float = 0.001 # I think it was overfitting and had high learning rate. So, decreasing. # increasing because bigger batch size\n",
    "    weight_decay: float = 1e-4    # also adding weight decay\n",
    "    epochs: int = 1000\n",
    "    patience: int = 3              # Early stopping patience\n",
    "    min_delta: float = 0.001       # Early stopping minimum improvement\n",
    "    device: str = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "    base_dir: str = '/kaggle/working' if os.path.exists('/kaggle/working') else os.getcwd()\n",
    "    \n",
    "    # Automatically builds paths relative to the correct environment base\n",
    "    log_file: str = None\n",
    "    csv_file: str = None\n",
    "    data_dir: str = None\n",
    "\n",
    "    def __post_init__(self):\n",
    "        \"\"\"Initializes full paths dynamically after class creation.\"\"\"\n",
    "        self.log_file = os.path.join(self.base_dir, 'app.log')\n",
    "        self.csv_file = os.path.join(self.base_dir, 'results.csv')\n",
    "        self.data_dir = os.path.join(self.base_dir, 'data')\n",
    "\n",
    "    device: str = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "\n",
    "\n",
    "# =====================================================================\n",
    "# 2. UTILITY & SETUP FUNCTIONS\n",
    "# =====================================================================\n",
    "def setup_logger(log_file: str):\n",
    "    \"\"\"Configures logging to output to both a file and the notebook cell.\"\"\"\n",
    "    logger = logging.getLogger()\n",
    "    logger.setLevel(logging.INFO)\n",
    "    \n",
    "    # Clear existing handlers to prevent duplicate prints in notebooks\n",
    "    if logger.hasHandlers():\n",
    "        logger.handlers.clear()\n",
    "        \n",
    "    formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s', datefmt='%Y-%m-%d %H:%M:%S')\n",
    "    \n",
    "    # File Handler\n",
    "    fh = logging.FileHandler(log_file, mode='a')\n",
    "    fh.setFormatter(formatter)\n",
    "    logger.addHandler(fh)\n",
    "    \n",
    "    # Console (Stream) Handler for Notebooks\n",
    "    ch = logging.StreamHandler()\n",
    "    ch.setFormatter(logging.Formatter('%(levelname)s - %(message)s'))\n",
    "    logger.addHandler(ch)\n",
    "\n",
    "def get_dataloaders(config: Config):\n",
    "    '''\n",
    "    # without transformations, I got only 8% accuracy :sigh:\n",
    "    but the training loss is also not decreasing.. so I may need more layers too.\n",
    "    INFO - Epoch 1 | Train Loss: 1.0704 | Test Loss: 1.0000 | Test Acc: 8.46%\n",
    "    INFO - Epoch 2 | Train Loss: 1.0000 | Test Loss: 1.0000 | Test Acc: 9.10%\n",
    "    INFO - Epoch 3 | Train Loss: 1.0000 | Test Loss: 1.0000 | Test Acc: 8.87%\n",
    "    INFO - --> Loss plateaued. Patience: 1/3\n",
    "    INFO - Epoch 4 | Train Loss: 1.0000 | Test Loss: 1.0000 | Test Acc: 8.20%\n",
    "    INFO - --> Loss plateaued. Patience: 2/3\n",
    "    INFO - Epoch 5 | Train Loss: 1.0000 | Test Loss: 1.0000 | Test Acc: 8.43%\n",
    "    '''\n",
    "    train_transforms = v2.Compose([\n",
    "        v2.Resize(256),\n",
    "        v2.RandomResizedCrop(224, scale=(0.8, 1.0)),\n",
    "        v2.RandomHorizontalFlip(p=0.5),\n",
    "        v2.RandomRotation(degrees=(-30, 30)),\n",
    "        v2.RandomApply([v2.Grayscale(num_output_channels=3)], p=0.1),\n",
    "        v2.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),\n",
    "        v2.ToImage(),\n",
    "        v2.ToDtype(torch.float32, scale=True),\n",
    "        v2.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n",
    "    ])\n",
    "    \n",
    "    # 2. Validation/Test transforms: No randomness, only preprocessing\n",
    "    val_transforms = v2.Compose([\n",
    "        v2.Resize(256),\n",
    "        v2.CenterCrop(224),\n",
    "        v2.ToImage(),\n",
    "        v2.ToDtype(torch.float32, scale=True),\n",
    "        v2.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n",
    "    ])\n",
    "\n",
    "    \"\"\"Downloads data and returns training and testing dataloaders.\"\"\"\n",
    "    train_dataset = torchvision.datasets.Imagenette( # switched to this for autodownload feature.. (gemini recommended)\n",
    "        root='./data', \n",
    "        split='train', \n",
    "        download=True,       # This works automatically!\n",
    "        transform=train_transforms\n",
    "    )\n",
    "\n",
    "    # Download and load the Validation Data\n",
    "    test_dataset = torchvision.datasets.Imagenette(\n",
    "        root='./data', \n",
    "        split='val', \n",
    "        download=True,\n",
    "        transform=val_transforms\n",
    "    )\n",
    "    train_loader = DataLoader(dataset=train_dataset, batch_size=config.batch_size, shuffle=True, num_workers=4, pin_memory=True, persistent_workers=True)\n",
    "    test_loader = DataLoader(dataset=test_dataset, batch_size=config.batch_size, shuffle=False, num_workers=2, pin_memory=True, persistent_workers=True)\n",
    "\n",
    "    return train_loader, test_loader\n",
    "\n",
    "def log_results_to_csv(config: Config, filename: str, train_loss: float, test_loss: float, test_acc: float):\n",
    "    \"\"\"Appends execution metrics to a local CSV file.\"\"\"\n",
    "    timestamp_str = datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n",
    "    file_exists = os.path.isfile(config.csv_file)\n",
    "\n",
    "    with open(config.csv_file, mode='a', newline='') as f:\n",
    "        writer = csv.writer(f)\n",
    "        if not file_exists:\n",
    "            writer.writerow(['Timestamp', 'Model File', 'Avg Train Loss', 'Test Loss', 'Test Accuracy (%)'])\n",
    "            \n",
    "        writer.writerow([\n",
    "            timestamp_str,\n",
    "            filename,\n",
    "            f\"{train_loss:.4f}\" if train_loss is not None else \"N/A\",\n",
    "            f\"{test_loss:.4f}\",\n",
    "            f\"{test_acc * 100:.2f}%\"\n",
    "        ])\n",
    "    logging.info(f\"Successfully appended execution results to {config.csv_file}\")\n",
    "\n",
    "# =====================================================================\n",
    "# 3. MODEL ARCHITECTURE\n",
    "# =====================================================================\n",
    "class Flatten(nn.Module):\n",
    "    def forward(self, x):\n",
    "        return x.view(x.size(0), -1)\n",
    "\n",
    "\n",
    "class CustomResNet(nn.Module):\n",
    "    # kind of vibe - coded so that GPU is used properly.\n",
    "    '''\n",
    "    In your original function, variables like down_16_to_32 are created as isolated, local Python variables.When you pass down_16_to_32 into BasicBlock(..., downsample=down_16_to_32), PyTorch treats it as an unlinked, external pointer.When nn.DataParallel duplicates your model across both T4 cards, it reads the main nn.Sequential pipeline and copies those layers to GPU 1.However, because those downsampling variables are sitting in local function scope rather than being registered to a parent model object, nn.DataParallel fails to copy them to the second GPU.The second GPU will attempt to compute the residual connection, look for the downsampling layers, find them missing on its own hardware, and throw a device mismatch crash.\n",
    "    Need to understand this better\n",
    "    @TODO:Manas\n",
    "    '''\n",
    "    def __init__(self, num_classes=10):\n",
    "        super(CustomResNet, self).__init__()\n",
    "        \n",
    "        # 1. Initial Convolution block (Input: 3 -> 32 channels)\n",
    "        self.init_block = nn.Sequential(\n",
    "            nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False),\n",
    "            nn.BatchNorm2d(64),\n",
    "            nn.ReLU(inplace=True),\n",
    "            nn.MaxPool2d(kernel_size=2, stride=2)\n",
    "        )\n",
    "        \n",
    "        # 2. Updated downsampling shortcuts to match the new channel expansions\n",
    "        self.down_32_to_64 = nn.Sequential(\n",
    "            nn.Conv2d(64, 128, kernel_size=1, stride=2, bias=False),\n",
    "            nn.BatchNorm2d(128)\n",
    "        )\n",
    "        self.down_64_to_128 = nn.Sequential(\n",
    "            nn.Conv2d(128, 256, kernel_size=1, stride=2, bias=False),\n",
    "            nn.BatchNorm2d(256)\n",
    "        )\n",
    "        self.down_128_to_256 = nn.Sequential(\n",
    "            nn.Conv2d(256, 512, kernel_size=1, stride=2, bias=False),\n",
    "            nn.BatchNorm2d(512)\n",
    "        )\n",
    "        \n",
    "        # 3. Residual Blocks configured with the expanded channel settings\n",
    "        self.layer1 = BasicBlock(inplanes=64, planes=64)\n",
    "        self.layer2 = BasicBlock(inplanes=64, planes=128, stride=2, downsample=self.down_32_to_64)\n",
    "        self.layer3 = BasicBlock(inplanes=128, planes=256, stride=2, downsample=self.down_64_to_128)\n",
    "        self.layer4 = BasicBlock(inplanes=256, planes=512, stride=2, downsample=self.down_128_to_256)\n",
    "\n",
    "        # 4. Classifier Head\n",
    "        self.classifier = nn.Sequential(\n",
    "            nn.AdaptiveAvgPool2d((1, 1)),\n",
    "            nn.Flatten(),\n",
    "            nn.Dropout(p=0.1),       # Reduced from 0.3 to combat underfitting!\n",
    "            nn.Linear(512, num_classes), # Changed from 128 to 256\n",
    "            nn.LogSoftmax(dim=1)\n",
    "        )\n",
    "\n",
    "    def forward(self, x):\n",
    "        # Explicit execution path through the layers\n",
    "        x = self.init_block(x)\n",
    "        x = self.layer1(x)\n",
    "        x = self.layer2(x)\n",
    "        x = self.layer3(x)\n",
    "        x = self.layer4(x)\n",
    "        x = self.classifier(x)\n",
    "        return x\n",
    "\n",
    "# Function to initialize and automatically handle CPU vs T4x2 Multi-GPU deployment\n",
    "def create_model():\n",
    "    model = CustomResNet(num_classes=10)\n",
    "    \n",
    "    device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "    \n",
    "    if torch.cuda.device_count() > 1:\n",
    "        print(f\"🚀 Using {torch.cuda.device_count()} GPUs for training!\")\n",
    "        model = nn.DataParallel(model)\n",
    "        \n",
    "    return model.to(device)\n",
    "\n",
    "\n",
    "def load_latest_checkpoint(model: nn.Module, optimizer: optim.Optimizer, config: Config):\n",
    "    \"\"\"Loads the latest model weights and optimizer state if they exist.\"\"\"\n",
    "    saved_models = glob.glob(\"model_*.pth\")\n",
    "    if config.use_latest_model and saved_models:\n",
    "        latest_model_file = max(saved_models, key=os.path.getmtime)\n",
    "        logging.info(f\"--> Found existing models. Loading weights from: {latest_model_file}\")\n",
    "        \n",
    "        checkpoint = torch.load(latest_model_file, map_location=config.device)\n",
    "        model.load_state_dict(checkpoint['model_state_dict'])\n",
    "        optimizer.load_state_dict(checkpoint['optimizer_state_dict'])\n",
    "        \n",
    "        return latest_model_file, checkpoint.get('epoch', 0)\n",
    "    \n",
    "    logging.info(\"--> Starting from scratch (no previous models loaded).\")\n",
    "    return None, 0\n",
    "\n",
    "# =====================================================================\n",
    "# 4. TRAINING & EVALUATION LOGIC\n",
    "# =====================================================================\n",
    "def calculate_loss_and_metrics(outputs, labels, criterion):\n",
    "    \"\"\"Centralized loss calculation and accuracy metrics for MNIST.\"\"\"\n",
    "    # Convert labels to one-hot for MSE Loss\n",
    "    # one_hot_labels = nn.functional.one_hot(labels, num_classes=10).float()\n",
    "    loss = criterion(outputs, labels) # NLLLoss expects raw values..\n",
    "    \n",
    "    # Calculate accuracy\n",
    "    _, predicted = torch.max(outputs, 1)\n",
    "    correct = (predicted == labels).sum().item()\n",
    "    \n",
    "    return loss, correct\n",
    "\n",
    "def train_epoch(model, dataloader, optimizer, criterion, config):\n",
    "    \"\"\"Handles a single full pass through the training data.\"\"\"\n",
    "    model.train()\n",
    "    running_loss = 0.0\n",
    "    \n",
    "    for images, labels in dataloader:\n",
    "        images, labels = images.float().to(config.device), labels.to(config.device)\n",
    "        \n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(images)\n",
    "        loss, _ = calculate_loss_and_metrics(outputs, labels, criterion)\n",
    "        \n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        running_loss += loss.item()\n",
    "        \n",
    "    return running_loss / len(dataloader)\n",
    "\n",
    "def evaluate(model, dataloader, criterion, config):\n",
    "    \"\"\"Evaluates the model on the testing data.\"\"\"\n",
    "    model.eval()\n",
    "    total_loss = 0.0\n",
    "    correct_predictions = 0\n",
    "    total_samples = 0\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        for images, labels in dataloader:\n",
    "            images, labels = images.float().to(config.device), labels.to(config.device)\n",
    "            outputs = model(images)\n",
    "            \n",
    "            loss, correct = calculate_loss_and_metrics(outputs, labels, criterion)\n",
    "            total_loss += loss.item()\n",
    "            correct_predictions += correct\n",
    "            total_samples += labels.size(0)\n",
    "            \n",
    "    avg_loss = total_loss / total_samples\n",
    "    accuracy = correct_predictions / total_samples\n",
    "    return avg_loss, accuracy\n",
    "\n",
    "# =====================================================================\n",
    "# 5. MAIN EXECUTION\n",
    "# =====================================================================\n",
    "def main():\n",
    "    # 1. Initialize config and logging\n",
    "    config = Config()\n",
    "    setup_logger(config.log_file)\n",
    "    logging.info(f\"Using device: {config.device}\")\n",
    "    \n",
    "    # 2. Setup Data, Model, Optimizer, and Loss\n",
    "    train_loader, test_loader = get_dataloaders(config)\n",
    "    \n",
    "    model = create_model().to(config.device)\n",
    "    logging.info(f\"Network Architecture Initialized\")\n",
    "    \n",
    "    criterion = nn.NLLLoss()\n",
    "    optimizer = optim.Adam(model.parameters(), lr=config.learning_rate, weight_decay=config.weight_decay)\n",
    "    scheduler = optim.lr_scheduler.CosineAnnealingLR(\n",
    "        optimizer, \n",
    "        T_max=config.epochs, \n",
    "        eta_min=1e-6  # The minimum learning rate at the end of training\n",
    "    )    \n",
    "    # 3. Load checkpoint if applicable\n",
    "    latest_model_file, start_epoch = load_latest_checkpoint(model, optimizer, config)\n",
    "    \n",
    "    # 4. Training Loop\n",
    "    final_filename = latest_model_file\n",
    "    final_train_loss = None\n",
    "    \n",
    "    if config.train_model:\n",
    "        timestamp = datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "        writer = SummaryWriter(f'runs/{timestamp}')\n",
    "        \n",
    "        best_loss = float('inf')\n",
    "        patience_counter = 0\n",
    "        final_epoch = start_epoch\n",
    "        \n",
    "        for epoch in range(start_epoch, config.epochs):\n",
    "            # Train\n",
    "            avg_train_loss = train_epoch(model, train_loader, optimizer, criterion, config)\n",
    "            final_train_loss = avg_train_loss\n",
    "            final_epoch = epoch\n",
    "            \n",
    "            # Evaluate\n",
    "            test_loss, test_accuracy = evaluate(model, test_loader, criterion, config)\n",
    "            # Log metrics\n",
    "            logging.info(f\"Epoch {epoch+1} | Train Loss: {avg_train_loss:.4f} | Test Loss: {test_loss:.4f} | Test Acc: {test_accuracy*100:.2f}%\")\n",
    "            writer.add_scalar('Loss/Train', avg_train_loss, epoch)\n",
    "            writer.add_scalar('Loss/Validation', test_loss, epoch)\n",
    "            writer.add_scalar('Accuracy/Validation', test_accuracy, epoch)\n",
    "            scheduler.step()\n",
    "\n",
    "            # Early Stopping\n",
    "            if avg_train_loss < (best_loss - config.min_delta):\n",
    "                best_loss = avg_train_loss\n",
    "                patience_counter = 0\n",
    "            else:\n",
    "                patience_counter += 1\n",
    "                logging.info(f\"--> Loss plateaued. Patience: {patience_counter}/{config.patience}\")\n",
    "                \n",
    "            if patience_counter >= config.patience:\n",
    "                logging.info(f\"Stopping early at epoch {epoch+1}! No improvement in {config.patience} epochs.\")\n",
    "                break\n",
    "                \n",
    "        # Save the newly trained model\n",
    "        final_filename = f\"/kaggle/working/model_{timestamp}.pth\"\n",
    "        checkpoint = {\n",
    "            'epoch': final_epoch,\n",
    "            'model_state_dict': model.state_dict(),\n",
    "            'optimizer_state_dict': optimizer.state_dict(),\n",
    "            'loss': final_train_loss\n",
    "        }\n",
    "        torch.save(checkpoint, final_filename)\n",
    "        logging.info(f\"Saved new checkpoint: {final_filename}\")\n",
    "\n",
    "    # 5. Final Evaluation & CSV Logging (runs even if we just loaded a model and skipped training)\n",
    "    logging.info(\"Running final evaluation...\")\n",
    "    final_test_loss, final_test_acc = evaluate(model, test_loader, criterion, config)\n",
    "    log_results_to_csv(config, final_filename, final_train_loss, final_test_loss, final_test_acc)\n",
    "\n",
    "# Execute if run as a script (or run this cell in a notebook)\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.13"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 4031.177389,
   "end_time": "2026-07-21T22:30:01.324932+00:00",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2026-07-21T21:22:50.147543+00:00",
   "version": "2.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
