{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c88ce755",
   "metadata": {
    "_cell_guid": "757f7df2-4bb4-421d-ad25-86efd4d77918",
    "_uuid": "1a7c8e0a-f882-4307-bece-8c5a7f8e4607",
    "collapsed": false,
    "execution": {
     "iopub.execute_input": "2026-07-22T03:43:29.780690Z",
     "iopub.status.busy": "2026-07-22T03:43:29.780159Z",
     "iopub.status.idle": "2026-07-22T04:49:01.773595Z",
     "shell.execute_reply": "2026-07-22T04:49:01.772795Z"
    },
    "jupyter": {
     "outputs_hidden": false
    },
    "papermill": {
     "duration": 3931.998506,
     "end_time": "2026-07-22T04:49:01.775477+00:00",
     "exception": false,
     "start_time": "2026-07-22T03:43:29.776971+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO - Using device: cuda\n",
      "100%|██████████| 1.56G/1.56G [01:34<00:00, 16.4MB/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🚀 Using 2 GPUs for training!\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO - Network Architecture Initialized\n",
      "INFO - --> Starting from scratch (no previous models loaded).\n",
      "INFO - Epoch 1 | Train Loss: 1.9641 | Test Loss: 0.0258 | Test Acc: 46.04%\n",
      "INFO - Epoch 2 | Train Loss: 1.6536 | Test Loss: 0.0267 | Test Acc: 42.17%\n",
      "INFO - Epoch 3 | Train Loss: 1.4639 | Test Loss: 0.0321 | Test Acc: 44.20%\n",
      "INFO - Epoch 4 | Train Loss: 1.3447 | Test Loss: 0.0288 | Test Acc: 49.38%\n",
      "INFO - Epoch 5 | Train Loss: 1.2135 | Test Loss: 0.0215 | Test Acc: 57.02%\n",
      "INFO - Epoch 6 | Train Loss: 1.1534 | Test Loss: 0.0258 | Test Acc: 51.29%\n",
      "INFO - Epoch 7 | Train Loss: 1.0868 | Test Loss: 0.0161 | Test Acc: 67.59%\n",
      "INFO - Epoch 8 | Train Loss: 1.0120 | Test Loss: 0.0187 | Test Acc: 62.09%\n",
      "INFO - Epoch 9 | Train Loss: 0.9815 | Test Loss: 0.0151 | Test Acc: 69.30%\n",
      "INFO - Epoch 10 | Train Loss: 0.9328 | Test Loss: 0.0176 | Test Acc: 64.61%\n",
      "INFO - Epoch 11 | Train Loss: 0.8909 | Test Loss: 0.0148 | Test Acc: 69.76%\n",
      "INFO - Epoch 12 | Train Loss: 0.8437 | Test Loss: 0.0166 | Test Acc: 67.06%\n",
      "INFO - Epoch 13 | Train Loss: 0.8156 | Test Loss: 0.0140 | Test Acc: 72.41%\n",
      "INFO - Epoch 14 | Train Loss: 0.8032 | Test Loss: 0.0156 | Test Acc: 68.79%\n",
      "INFO - Epoch 15 | Train Loss: 0.7568 | Test Loss: 0.0121 | Test Acc: 76.59%\n",
      "INFO - Epoch 16 | Train Loss: 0.7172 | Test Loss: 0.0133 | Test Acc: 74.73%\n",
      "INFO - Epoch 17 | Train Loss: 0.7153 | Test Loss: 0.0119 | Test Acc: 77.40%\n",
      "INFO - Epoch 18 | Train Loss: 0.7192 | Test Loss: 0.0127 | Test Acc: 74.60%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 19 | Train Loss: 0.6538 | Test Loss: 0.0118 | Test Acc: 76.08%\n",
      "INFO - Epoch 20 | Train Loss: 0.6514 | Test Loss: 0.0121 | Test Acc: 76.15%\n",
      "INFO - Epoch 21 | Train Loss: 0.6278 | Test Loss: 0.0117 | Test Acc: 76.31%\n",
      "INFO - Epoch 22 | Train Loss: 0.6013 | Test Loss: 0.0114 | Test Acc: 77.50%\n",
      "INFO - Epoch 23 | Train Loss: 0.6078 | Test Loss: 0.0109 | Test Acc: 78.93%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 24 | Train Loss: 0.5823 | Test Loss: 0.0114 | Test Acc: 77.15%\n",
      "INFO - Epoch 25 | Train Loss: 0.5689 | Test Loss: 0.0100 | Test Acc: 80.51%\n",
      "INFO - Epoch 26 | Train Loss: 0.5658 | Test Loss: 0.0122 | Test Acc: 77.55%\n",
      "INFO - Epoch 27 | Train Loss: 0.5255 | Test Loss: 0.0109 | Test Acc: 78.39%\n",
      "INFO - Epoch 28 | Train Loss: 0.5182 | Test Loss: 0.0104 | Test Acc: 79.26%\n",
      "INFO - Epoch 29 | Train Loss: 0.5244 | Test Loss: 0.0118 | Test Acc: 76.05%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 30 | Train Loss: 0.4999 | Test Loss: 0.0182 | Test Acc: 68.36%\n",
      "INFO - Epoch 31 | Train Loss: 0.4938 | Test Loss: 0.0143 | Test Acc: 74.34%\n",
      "INFO - Epoch 32 | Train Loss: 0.4670 | Test Loss: 0.0140 | Test Acc: 73.63%\n",
      "INFO - Epoch 33 | Train Loss: 0.4767 | Test Loss: 0.0108 | Test Acc: 80.28%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 34 | Train Loss: 0.4607 | Test Loss: 0.0092 | Test Acc: 82.11%\n",
      "INFO - Epoch 35 | Train Loss: 0.4330 | Test Loss: 0.0091 | Test Acc: 82.45%\n",
      "INFO - Epoch 36 | Train Loss: 0.4153 | Test Loss: 0.0113 | Test Acc: 78.37%\n",
      "INFO - Epoch 37 | Train Loss: 0.4246 | Test Loss: 0.0092 | Test Acc: 81.99%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 38 | Train Loss: 0.4088 | Test Loss: 0.0107 | Test Acc: 79.34%\n",
      "INFO - Epoch 39 | Train Loss: 0.3906 | Test Loss: 0.0095 | Test Acc: 81.63%\n",
      "INFO - Epoch 40 | Train Loss: 0.3942 | Test Loss: 0.0115 | Test Acc: 79.80%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 41 | Train Loss: 0.3767 | Test Loss: 0.0108 | Test Acc: 80.36%\n",
      "INFO - Epoch 42 | Train Loss: 0.3632 | Test Loss: 0.0097 | Test Acc: 81.94%\n",
      "INFO - Epoch 43 | Train Loss: 0.3538 | Test Loss: 0.0089 | Test Acc: 83.46%\n",
      "INFO - Epoch 44 | Train Loss: 0.3330 | Test Loss: 0.0111 | Test Acc: 81.04%\n",
      "INFO - Epoch 45 | Train Loss: 0.3447 | Test Loss: 0.0100 | Test Acc: 81.76%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 46 | Train Loss: 0.3418 | Test Loss: 0.0101 | Test Acc: 80.69%\n",
      "INFO - --> Loss plateaued. Patience: 2/3\n",
      "INFO - Epoch 47 | Train Loss: 0.3165 | Test Loss: 0.0092 | Test Acc: 82.96%\n",
      "INFO - Epoch 48 | Train Loss: 0.3229 | Test Loss: 0.0099 | Test Acc: 82.14%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 49 | Train Loss: 0.3100 | Test Loss: 0.0086 | Test Acc: 84.25%\n",
      "INFO - Epoch 50 | Train Loss: 0.3008 | Test Loss: 0.0108 | Test Acc: 80.59%\n",
      "INFO - Epoch 51 | Train Loss: 0.2819 | Test Loss: 0.0090 | Test Acc: 82.24%\n",
      "INFO - Epoch 52 | Train Loss: 0.2789 | Test Loss: 0.0094 | Test Acc: 82.42%\n",
      "INFO - Epoch 53 | Train Loss: 0.2760 | Test Loss: 0.0105 | Test Acc: 81.55%\n",
      "INFO - Epoch 54 | Train Loss: 0.2733 | Test Loss: 0.0101 | Test Acc: 81.81%\n",
      "INFO - Epoch 55 | Train Loss: 0.2830 | Test Loss: 0.0087 | Test Acc: 84.66%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 56 | Train Loss: 0.2522 | Test Loss: 0.0075 | Test Acc: 86.55%\n",
      "INFO - Epoch 57 | Train Loss: 0.2686 | Test Loss: 0.0092 | Test Acc: 82.90%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 58 | Train Loss: 0.2454 | Test Loss: 0.0077 | Test Acc: 85.35%\n",
      "INFO - Epoch 59 | Train Loss: 0.2512 | Test Loss: 0.0088 | Test Acc: 83.97%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 60 | Train Loss: 0.2400 | Test Loss: 0.0100 | Test Acc: 83.72%\n",
      "INFO - Epoch 61 | Train Loss: 0.2472 | Test Loss: 0.0088 | Test Acc: 83.75%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 62 | Train Loss: 0.2465 | Test Loss: 0.0098 | Test Acc: 82.80%\n",
      "INFO - --> Loss plateaued. Patience: 2/3\n",
      "INFO - Epoch 63 | Train Loss: 0.2031 | Test Loss: 0.0076 | Test Acc: 86.57%\n",
      "INFO - Epoch 64 | Train Loss: 0.2194 | Test Loss: 0.0078 | Test Acc: 86.19%\n",
      "INFO - --> Loss plateaued. Patience: 1/3\n",
      "INFO - Epoch 65 | Train Loss: 0.2061 | Test Loss: 0.0095 | Test Acc: 83.67%\n",
      "INFO - --> Loss plateaued. Patience: 2/3\n",
      "INFO - Epoch 66 | Train Loss: 0.2459 | Test Loss: 0.0109 | Test Acc: 82.32%\n",
      "INFO - --> Loss plateaued. Patience: 3/3\n",
      "INFO - Stopping early at epoch 66! No improvement in 3 epochs.\n",
      "INFO - Saved new checkpoint: /kaggle/working/model_20260722_034541.pth\n",
      "INFO - Running final evaluation...\n",
      "INFO - Successfully appended execution results to /kaggle/working/results.csv\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import csv\n",
    "import glob\n",
    "import logging\n",
    "from datetime import datetime\n",
    "from dataclasses import dataclass\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "import torchvision\n",
    "import torchvision.transforms as transforms\n",
    "from torch.utils.data import DataLoader\n",
    "from torch.utils.tensorboard import SummaryWriter\n",
    "from torchvision.transforms import v2\n",
    "from torchvision.models.resnet import BasicBlock\n",
    "\n",
    "# =====================================================================\n",
    "# 1. CONFIGURATION (Notebook Friendly)\n",
    "# =====================================================================\n",
    "@dataclass\n",
    "class Config:\n",
    "    \"\"\"Replaces argparse for seamless Jupyter Notebook usage.\"\"\"\n",
    "    use_latest_model: bool = True\n",
    "    train_model: bool = True       # Set to False if you only want to evaluate\n",
    "    batch_size: int = 64 # let's try mini-batch SGD now. # increasing because GPU utilization is low.\n",
    "    learning_rate: float = 0.001 # I think it was overfitting and had high learning rate. So, decreasing. # increasing because bigger batch size\n",
    "    weight_decay: float = 1e-4    # also adding weight decay\n",
    "    epochs: int = 1000\n",
    "    patience: int = 3              # Early stopping patience\n",
    "    min_delta: float = 0.001       # Early stopping minimum improvement\n",
    "    device: str = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "    base_dir: str = '/kaggle/working' if os.path.exists('/kaggle/working') else os.getcwd()\n",
    "    \n",
    "    # Automatically builds paths relative to the correct environment base\n",
    "    log_file: str = None\n",
    "    csv_file: str = None\n",
    "    data_dir: str = None\n",
    "\n",
    "    def __post_init__(self):\n",
    "        \"\"\"Initializes full paths dynamically after class creation.\"\"\"\n",
    "        self.log_file = os.path.join(self.base_dir, 'app.log')\n",
    "        self.csv_file = os.path.join(self.base_dir, 'results.csv')\n",
    "        self.data_dir = os.path.join(self.base_dir, 'data')\n",
    "\n",
    "    device: str = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "\n",
    "\n",
    "# =====================================================================\n",
    "# 2. UTILITY & SETUP FUNCTIONS\n",
    "# =====================================================================\n",
    "def setup_logger(log_file: str):\n",
    "    \"\"\"Configures logging to output to both a file and the notebook cell.\"\"\"\n",
    "    logger = logging.getLogger()\n",
    "    logger.setLevel(logging.INFO)\n",
    "    \n",
    "    # Clear existing handlers to prevent duplicate prints in notebooks\n",
    "    if logger.hasHandlers():\n",
    "        logger.handlers.clear()\n",
    "        \n",
    "    formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s', datefmt='%Y-%m-%d %H:%M:%S')\n",
    "    \n",
    "    # File Handler\n",
    "    fh = logging.FileHandler(log_file, mode='a')\n",
    "    fh.setFormatter(formatter)\n",
    "    logger.addHandler(fh)\n",
    "    \n",
    "    # Console (Stream) Handler for Notebooks\n",
    "    ch = logging.StreamHandler()\n",
    "    ch.setFormatter(logging.Formatter('%(levelname)s - %(message)s'))\n",
    "    logger.addHandler(ch)\n",
    "\n",
    "def get_dataloaders(config: Config):\n",
    "    '''\n",
    "    # without transformations, I got only 8% accuracy :sigh:\n",
    "    but the training loss is also not decreasing.. so I may need more layers too.\n",
    "    INFO - Epoch 1 | Train Loss: 1.0704 | Test Loss: 1.0000 | Test Acc: 8.46%\n",
    "    INFO - Epoch 2 | Train Loss: 1.0000 | Test Loss: 1.0000 | Test Acc: 9.10%\n",
    "    INFO - Epoch 3 | Train Loss: 1.0000 | Test Loss: 1.0000 | Test Acc: 8.87%\n",
    "    INFO - --> Loss plateaued. Patience: 1/3\n",
    "    INFO - Epoch 4 | Train Loss: 1.0000 | Test Loss: 1.0000 | Test Acc: 8.20%\n",
    "    INFO - --> Loss plateaued. Patience: 2/3\n",
    "    INFO - Epoch 5 | Train Loss: 1.0000 | Test Loss: 1.0000 | Test Acc: 8.43%\n",
    "    '''\n",
    "    train_transforms = v2.Compose([\n",
    "        v2.Resize(256),\n",
    "        v2.RandomResizedCrop(224, scale=(0.8, 1.0)),\n",
    "        v2.RandomHorizontalFlip(p=0.5),\n",
    "        v2.RandomRotation(degrees=(-30, 30)),\n",
    "        v2.RandomApply([v2.Grayscale(num_output_channels=3)], p=0.1),\n",
    "        v2.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),\n",
    "        v2.ToImage(),\n",
    "        v2.ToDtype(torch.float32, scale=True),\n",
    "        v2.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n",
    "    ])\n",
    "    \n",
    "    # 2. Validation/Test transforms: No randomness, only preprocessing\n",
    "    val_transforms = v2.Compose([\n",
    "        v2.Resize(256),\n",
    "        v2.CenterCrop(224),\n",
    "        v2.ToImage(),\n",
    "        v2.ToDtype(torch.float32, scale=True),\n",
    "        v2.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n",
    "    ])\n",
    "\n",
    "    \"\"\"Downloads data and returns training and testing dataloaders.\"\"\"\n",
    "    train_dataset = torchvision.datasets.Imagenette( # switched to this for autodownload feature.. (gemini recommended)\n",
    "        root='./data', \n",
    "        split='train', \n",
    "        download=True,       # This works automatically!\n",
    "        transform=train_transforms\n",
    "    )\n",
    "\n",
    "    # Download and load the Validation Data\n",
    "    test_dataset = torchvision.datasets.Imagenette(\n",
    "        root='./data', \n",
    "        split='val', \n",
    "        download=True,\n",
    "        transform=val_transforms\n",
    "    )\n",
    "    train_loader = DataLoader(dataset=train_dataset, batch_size=config.batch_size, shuffle=True, num_workers=4, pin_memory=True, persistent_workers=True)\n",
    "    test_loader = DataLoader(dataset=test_dataset, batch_size=config.batch_size, shuffle=False, num_workers=2, pin_memory=True, persistent_workers=True)\n",
    "\n",
    "    return train_loader, test_loader\n",
    "\n",
    "def log_results_to_csv(config: Config, filename: str, train_loss: float, test_loss: float, test_acc: float):\n",
    "    \"\"\"Appends execution metrics to a local CSV file.\"\"\"\n",
    "    timestamp_str = datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n",
    "    file_exists = os.path.isfile(config.csv_file)\n",
    "\n",
    "    with open(config.csv_file, mode='a', newline='') as f:\n",
    "        writer = csv.writer(f)\n",
    "        if not file_exists:\n",
    "            writer.writerow(['Timestamp', 'Model File', 'Avg Train Loss', 'Test Loss', 'Test Accuracy (%)'])\n",
    "            \n",
    "        writer.writerow([\n",
    "            timestamp_str,\n",
    "            filename,\n",
    "            f\"{train_loss:.4f}\" if train_loss is not None else \"N/A\",\n",
    "            f\"{test_loss:.4f}\",\n",
    "            f\"{test_acc * 100:.2f}%\"\n",
    "        ])\n",
    "    logging.info(f\"Successfully appended execution results to {config.csv_file}\")\n",
    "\n",
    "# =====================================================================\n",
    "# 3. MODEL ARCHITECTURE\n",
    "# =====================================================================\n",
    "class Flatten(nn.Module):\n",
    "    def forward(self, x):\n",
    "        return x.view(x.size(0), -1)\n",
    "\n",
    "\n",
    "class CustomResNet(nn.Module):\n",
    "    # gemini implemented to see what accuracy I get...\n",
    "    def __init__(self, num_classes=10):\n",
    "        super(CustomResNet, self).__init__()\n",
    "        \n",
    "        # 1. Official ResNet-18 Stem (Input: 3 -> 64 channels, 7x7 conv with stride 2)\n",
    "        self.init_block = nn.Sequential(\n",
    "            nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=3, bias=False),\n",
    "            nn.BatchNorm2d(64),\n",
    "            nn.ReLU(inplace=True),\n",
    "            nn.MaxPool2d(kernel_size=3, stride=2, padding=1)\n",
    "        )\n",
    "        \n",
    "        # 2. Downsampling Shortcuts (Registered as self attributes for DataParallel safety)\n",
    "        self.down_64_to_128 = nn.Sequential(\n",
    "            nn.Conv2d(64, 128, kernel_size=1, stride=2, bias=False),\n",
    "            nn.BatchNorm2d(128)\n",
    "        )\n",
    "        self.down_128_to_256 = nn.Sequential(\n",
    "            nn.Conv2d(128, 256, kernel_size=1, stride=2, bias=False),\n",
    "            nn.BatchNorm2d(256)\n",
    "        )\n",
    "        self.down_256_to_512 = nn.Sequential(\n",
    "            nn.Conv2d(256, 512, kernel_size=1, stride=2, bias=False),\n",
    "            nn.BatchNorm2d(512)\n",
    "        )\n",
    "        \n",
    "        # 3. Stage 1 (64 channels) - 2 Blocks\n",
    "        self.layer1 = nn.Sequential(\n",
    "            BasicBlock(inplanes=64, planes=64),\n",
    "            BasicBlock(inplanes=64, planes=64)\n",
    "        )\n",
    "        \n",
    "        # Stage 2 (128 channels) - 2 Blocks (1st block downsamples)\n",
    "        self.layer2 = nn.Sequential(\n",
    "            BasicBlock(inplanes=64, planes=128, stride=2, downsample=self.down_64_to_128),\n",
    "            BasicBlock(inplanes=128, planes=128)\n",
    "        )\n",
    "        \n",
    "        # Stage 3 (256 channels) - 2 Blocks (1st block downsamples)\n",
    "        self.layer3 = nn.Sequential(\n",
    "            BasicBlock(inplanes=128, planes=256, stride=2, downsample=self.down_128_to_256),\n",
    "            BasicBlock(inplanes=256, planes=256)\n",
    "        )\n",
    "        \n",
    "        # Stage 4 (512 channels) - 2 Blocks (1st block downsamples)\n",
    "        self.layer4 = nn.Sequential(\n",
    "            BasicBlock(inplanes=256, planes=512, stride=2, downsample=self.down_256_to_512),\n",
    "            BasicBlock(inplanes=512, planes=512)\n",
    "        )\n",
    "\n",
    "        # 4. Classifier Head\n",
    "        self.classifier = nn.Sequential(\n",
    "            nn.AdaptiveAvgPool2d((1, 1)),\n",
    "            nn.Flatten(),\n",
    "            nn.Dropout(p=0.1),\n",
    "            nn.Linear(512, num_classes),\n",
    "            nn.LogSoftmax(dim=1)\n",
    "        )\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = self.init_block(x)\n",
    "        x = self.layer1(x)\n",
    "        x = self.layer2(x)\n",
    "        x = self.layer3(x)\n",
    "        x = self.layer4(x)\n",
    "        x = self.classifier(x)\n",
    "        return x\n",
    "\n",
    "# Function to initialize and automatically handle CPU vs T4x2 Multi-GPU deployment\n",
    "def create_model():\n",
    "    model = CustomResNet(num_classes=10)\n",
    "    \n",
    "    device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "    \n",
    "    if torch.cuda.device_count() > 1:\n",
    "        print(f\"🚀 Using {torch.cuda.device_count()} GPUs for training!\")\n",
    "        model = nn.DataParallel(model)\n",
    "        \n",
    "    return model.to(device)\n",
    "\n",
    "\n",
    "def load_latest_checkpoint(model: nn.Module, optimizer: optim.Optimizer, config: Config):\n",
    "    \"\"\"Loads the latest model weights and optimizer state if they exist.\"\"\"\n",
    "    saved_models = glob.glob(\"model_*.pth\")\n",
    "    if config.use_latest_model and saved_models:\n",
    "        latest_model_file = max(saved_models, key=os.path.getmtime)\n",
    "        logging.info(f\"--> Found existing models. Loading weights from: {latest_model_file}\")\n",
    "        \n",
    "        checkpoint = torch.load(latest_model_file, map_location=config.device)\n",
    "        model.load_state_dict(checkpoint['model_state_dict'])\n",
    "        optimizer.load_state_dict(checkpoint['optimizer_state_dict'])\n",
    "        \n",
    "        return latest_model_file, checkpoint.get('epoch', 0)\n",
    "    \n",
    "    logging.info(\"--> Starting from scratch (no previous models loaded).\")\n",
    "    return None, 0\n",
    "\n",
    "# =====================================================================\n",
    "# 4. TRAINING & EVALUATION LOGIC\n",
    "# =====================================================================\n",
    "def calculate_loss_and_metrics(outputs, labels, criterion):\n",
    "    \"\"\"Centralized loss calculation and accuracy metrics for MNIST.\"\"\"\n",
    "    # Convert labels to one-hot for MSE Loss\n",
    "    # one_hot_labels = nn.functional.one_hot(labels, num_classes=10).float()\n",
    "    loss = criterion(outputs, labels) # NLLLoss expects raw values..\n",
    "    \n",
    "    # Calculate accuracy\n",
    "    _, predicted = torch.max(outputs, 1)\n",
    "    correct = (predicted == labels).sum().item()\n",
    "    \n",
    "    return loss, correct\n",
    "\n",
    "def train_epoch(model, dataloader, optimizer, criterion, config):\n",
    "    \"\"\"Handles a single full pass through the training data.\"\"\"\n",
    "    model.train()\n",
    "    running_loss = 0.0\n",
    "    \n",
    "    for images, labels in dataloader:\n",
    "        images, labels = images.float().to(config.device), labels.to(config.device)\n",
    "        \n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(images)\n",
    "        loss, _ = calculate_loss_and_metrics(outputs, labels, criterion)\n",
    "        \n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        running_loss += loss.item()\n",
    "        \n",
    "    return running_loss / len(dataloader)\n",
    "\n",
    "def evaluate(model, dataloader, criterion, config):\n",
    "    \"\"\"Evaluates the model on the testing data.\"\"\"\n",
    "    model.eval()\n",
    "    total_loss = 0.0\n",
    "    correct_predictions = 0\n",
    "    total_samples = 0\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        for images, labels in dataloader:\n",
    "            images, labels = images.float().to(config.device), labels.to(config.device)\n",
    "            outputs = model(images)\n",
    "            \n",
    "            loss, correct = calculate_loss_and_metrics(outputs, labels, criterion)\n",
    "            total_loss += loss.item()\n",
    "            correct_predictions += correct\n",
    "            total_samples += labels.size(0)\n",
    "            \n",
    "    avg_loss = total_loss / total_samples\n",
    "    accuracy = correct_predictions / total_samples\n",
    "    return avg_loss, accuracy\n",
    "\n",
    "# =====================================================================\n",
    "# 5. MAIN EXECUTION\n",
    "# =====================================================================\n",
    "def main():\n",
    "    # 1. Initialize config and logging\n",
    "    config = Config()\n",
    "    setup_logger(config.log_file)\n",
    "    logging.info(f\"Using device: {config.device}\")\n",
    "    \n",
    "    # 2. Setup Data, Model, Optimizer, and Loss\n",
    "    train_loader, test_loader = get_dataloaders(config)\n",
    "    \n",
    "    model = create_model().to(config.device)\n",
    "    logging.info(f\"Network Architecture Initialized\")\n",
    "    \n",
    "    criterion = nn.NLLLoss()\n",
    "    optimizer = optim.Adam(model.parameters(), lr=config.learning_rate, weight_decay=config.weight_decay)\n",
    "    scheduler = optim.lr_scheduler.CosineAnnealingLR(\n",
    "        optimizer, \n",
    "        T_max=config.epochs, \n",
    "        eta_min=1e-6  # The minimum learning rate at the end of training\n",
    "    )    \n",
    "    # 3. Load checkpoint if applicable\n",
    "    latest_model_file, start_epoch = load_latest_checkpoint(model, optimizer, config)\n",
    "    \n",
    "    # 4. Training Loop\n",
    "    final_filename = latest_model_file\n",
    "    final_train_loss = None\n",
    "    \n",
    "    if config.train_model:\n",
    "        timestamp = datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "        writer = SummaryWriter(f'runs/{timestamp}')\n",
    "        \n",
    "        best_loss = float('inf')\n",
    "        patience_counter = 0\n",
    "        final_epoch = start_epoch\n",
    "        \n",
    "        for epoch in range(start_epoch, config.epochs):\n",
    "            # Train\n",
    "            avg_train_loss = train_epoch(model, train_loader, optimizer, criterion, config)\n",
    "            final_train_loss = avg_train_loss\n",
    "            final_epoch = epoch\n",
    "            \n",
    "            # Evaluate\n",
    "            test_loss, test_accuracy = evaluate(model, test_loader, criterion, config)\n",
    "            # Log metrics\n",
    "            logging.info(f\"Epoch {epoch+1} | Train Loss: {avg_train_loss:.4f} | Test Loss: {test_loss:.4f} | Test Acc: {test_accuracy*100:.2f}%\")\n",
    "            writer.add_scalar('Loss/Train', avg_train_loss, epoch)\n",
    "            writer.add_scalar('Loss/Validation', test_loss, epoch)\n",
    "            writer.add_scalar('Accuracy/Validation', test_accuracy, epoch)\n",
    "            scheduler.step()\n",
    "\n",
    "            # Early Stopping\n",
    "            if avg_train_loss < (best_loss - config.min_delta):\n",
    "                best_loss = avg_train_loss\n",
    "                patience_counter = 0\n",
    "            else:\n",
    "                patience_counter += 1\n",
    "                logging.info(f\"--> Loss plateaued. Patience: {patience_counter}/{config.patience}\")\n",
    "                \n",
    "            if patience_counter >= config.patience:\n",
    "                logging.info(f\"Stopping early at epoch {epoch+1}! No improvement in {config.patience} epochs.\")\n",
    "                break\n",
    "                \n",
    "        # Save the newly trained model\n",
    "        final_filename = f\"/kaggle/working/model_{timestamp}.pth\"\n",
    "        checkpoint = {\n",
    "            'epoch': final_epoch,\n",
    "            'model_state_dict': model.state_dict(),\n",
    "            'optimizer_state_dict': optimizer.state_dict(),\n",
    "            'loss': final_train_loss\n",
    "        }\n",
    "        torch.save(checkpoint, final_filename)\n",
    "        logging.info(f\"Saved new checkpoint: {final_filename}\")\n",
    "\n",
    "    # 5. Final Evaluation & CSV Logging (runs even if we just loaded a model and skipped training)\n",
    "    logging.info(\"Running final evaluation...\")\n",
    "    final_test_loss, final_test_acc = evaluate(model, test_loader, criterion, config)\n",
    "    log_results_to_csv(config, final_filename, final_train_loss, final_test_loss, final_test_acc)\n",
    "\n",
    "# Execute if run as a script (or run this cell in a notebook)\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.13"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 3938.693762,
   "end_time": "2026-07-22T04:49:06.224357+00:00",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2026-07-22T03:43:27.530595+00:00",
   "version": "2.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
